# This workflow will install Python dependencies and run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pyClarion test

on:
  push:
    branches: [ main, re-realizer ]
  pull_request:
    branches: [ main, re-realizer ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install pyClarion
      run: |
        python -m pip install -e .
    - name: Test with unittest
      run: |
        python -m unittest discover
    - name: Run examples
      run: |
        python examples/gradients.py
        python examples/lagged_features.py
